/* This file was generated by syncqt. */
#ifndef QT_QTQUICK_VERSION_H
#define QT_QTQUICK_VERSION_H

#define QTQUICK_VERSION_STR "5.9.6"

#define QTQUICK_VERSION 0x050906

#endif // QT_QTQUICK_VERSION_H
